[project]
name = "code-cleanup-automator"
version = "0.1.0"
description = "Automated Python hygiene"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pipreqs>=0.5.0",
    "pre-commit>=4.4.0",
    "pytest>=9.0.1",
    "radon>=6.0.1",
    "ruff>=0.14.4",
]
